name: Libretro
on:
  push:
    branches:
    - master
jobs:
  build-libretro:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile.libretro -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: GenPlusGX-libretro
        path: |
          ./*.dol
